### PR TITLE
Updates for psc-0.7

### PR DESCRIPTION
**Pull request by anttih**
This is a work in progress. It compiles, but only with the latest pulp. Need to wait for the grunt plugin to get updated and requires more testing.

### CODE REVIEW

**Comment by jdegoes** [comment]
Thanks, @anttih. Happy to keep this open till it's ready to merge and 0.7 comes out.

**Comment by garyb** [comment]
There's a version of the gulp plugin that works with the new compiler `0.5.0-rc.1`. I think you have to specify that as the lower bound for it to pick it up though, it won't match with `^0.5.0`.

**Comment by anttih** [comment]
Should `Control.Monad.Aff.Debug.Trace` be renamed to `Control.Monad.Aff.Console`? We could also rename `trace` in that module to `print`, to be in line with the Console module.

**Comment by garyb** [comment]
Yep, sounds good. :+1: Maybe add `log` in there while you're at it too.

**Comment by anttih** [comment]
This is looking good now. I replaced grunt with gulp but kept the build commands the same. The docs are now generated into separate files and linked to from the README.

**Comment by anttih** [comment]
Just noticed the `gulp psc` command is not generating the js bundle.

**Comment by jdegoes** [comment]
@anttih Can you squash commits so we get a clean commit history? Thanks!

**Comment by anttih** [comment]
Done. We'll need to wait for gulp-purescript in order for the build to work again, however. :(

**Comment by anttih** [comment]
@jdegoes @garyb Updated to the new gulp-purescript, and the build is working again.

Travis is running the build but we don't have .travis.yml. Should I add that?

**Comment by garyb** [comment]
Yes please, it's probably supposed to have one but we forgot to add a `!/.travis.yml` to the `.gitignore` file.

**Comment by jdegoes** [comment]
Thanks for your work on this @anttih! :+1:

**Pull request merged**
