### PR TITLE
Updates dependencies for PureScript 0.10

### LINKED ISSUE #73: doesn't build with psc 0.10
```shell
➜  purescript-aff git:(master) pulp build
* Building project in /Users/rvion/dev/purescript-aff
Error found:
in module Control.Monad.Aff.Console
at /Users/rvion/dev/purescript-aff/src/Control/Monad/Aff/Console.purs line 36, column 1 - line 36, column 34

  No type class instance was found for

    Control.Monad.Eff.Class.MonadEff ( console :: CONSOLE
                                     | t0
                                     )
                                     (Aff
                                        ( console :: CONSOLE
                                        | eff1
                                        )
                                     )

  The instance head contains unknown type variables. Consider adding a type annotation.

while checking that expression (compose liftEff) warnShow
  has type forall a eff.
             (Show a) => a
                         -> Aff
                              ( console :: CONSOLE
                              | eff
                              )
                              Unit
while applying a function compose
  of type forall b c d a. (Semigroupoid a) => a c d -> a b c -> a b d
  to argument liftEff
in value declaration warnShow

where eff1 is a rigid type variable
        bound at line 36, column 1 - line 36, column 34
      t0 is an unknown type

See https://github.com/purescript/purescript/wiki/Error-Code-NoInstanceFound for more information,
or to contribute content related to this error.
```

### PR DESCRIPTION
**Pull request by garyb**
Resolves #73

### CODE REVIEW

**Comment by garyb** [comment]
Rebased & included a fix for the other jscs warning that is now making master fail.

**Comment by bodil** [comment]
Could you tag a release as well? This is still blocking test-unit and thus all my things. :)

**Comment by garyb** [comment]
Just waiting on a decision on #75 since it'll be another breaking change if we do that after (ping @jdegoes).

**Comment by jdegoes** [comment]
Oops, sorry, I'm on it!

**Pull request merged**
